name: Set Environment Variables

on: [push]

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Set API KEY
        run: echo "API_KEY_TEST=${{ secrets.API_KEY_TEST }}" >> $GITHUB_ENV
